config:
  alignToGrid: True
  gridSize: 20
  textArea:
    fontFamily: monospace
    fontSize: 14px
  paths:
    configs: []
    checkpoints: []
    vae: []
    clip: []
    embeddings: []
    loras: []
