version: "3.9"

services:
  app:
    image: comfyui:1
    build: .

    ports:
      - "8188:8188"
    volumes:
      - ./models:/opt/comfy_ui/models
      - ./output:/opt/comfy_ui/output
      - ./input:/opt/comfy_ui/input
      - ./custom_nodes:/opt/comfy_ui/custom_nodes      

    environment:
      - CLI_ARGS=--listen --port 8188

    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ["0"]
                capabilities: [gpu]
