name: Test ComfyUI Mac With Default Workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore: 
      - 'tests/**'
      - 'tests-ui/**'
      - ".github/workflows/**"
      - "!.github/workflows/mac-os-test.yml"
  push:
    paths-ignore: 
      - 'tests/**'
      - 'tests-ui/**'
      - ".github/workflows/**"
      - "!.github/workflows/mac-os-test.yml"
  workflow_dispatch:


jobs:
  test-action:
    runs-on: m2
    steps:
    - name: Use ComfyUI GitHub Action
      uses: drip-art/comfy-action@main
      with:
        os: macos
        torch_ver: 'nightly'
        models-json: '{"v1-5-pruned-emaonly.ckpt": {"url": "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt", "directory": "checkpoints"}}'
        workflow_json_path: '.github/workflows/json_examples/workflow_api.json'
        timeout: 50
